name = "Stoic"
license = "MIT"
licenselink = "https://github.com/yihui/hugo-stoic/blob/master/LICENSE.md"
description = "A minimalist Hugo theme inspired by the academic theme, distill.pub, and stoicism."
homepage = "https://stoic.yihui.org"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.54"

[author]
  name = "Yihui Xie"
  homepage = "https://yihui.org"
